Refactored client and login logic to Garth for MFA support
yeekang-0311/garmin_planner pull request #1
Opened 2024-12-29 17:20 UTC by ehmsen

Hi
I stumpled upon your Garmin Planner project while searching for an exact solution you are solving.
I hate having to pay for TrainingPeaks or similar just to have my training plan synced to Garmin Connect, and it seems like Garmin is not going to create a way to manage custom training plans in Connect, so I was looking for exactly the project you have created. Thanks a lot!

However, I have MFA enabled on my Garmin account (I get a text with 6 digit code), so the current login method does not work for my use case.
But after looking around I found a maintained repo (https://github.com/matin/garth) that solves this problem and in addition it also simplifies the Garmin Planner a great deal (both code wise and dependency wise).

I have done some minimal testing using my own account.

Have a look at it and let me know what you think!

2025-01-02 12:09 UTC, yeekang-0311 requested changes
Hi, didnt know something like garth exists back then, it would have save me a lot of time coding lol. Thanks for the code refactoring. 

There is one change need to be done tho, need to catch the FileNotFound exception during very first login without .garth file. Calling .resume() will throw error.
<img width="378" alt="image" src="https://github.com/user-attachments/assets/e6c1cbb5-abef-46b4-ae5d-08fc456bc16b" />

2025-01-07 01:57 UTC, yeekang-0311 approved these changes

2025-01-07 01:59 UTC, merged

2025-01-07 02:06 UTC, yeekang-0311 commented
I havent got time to test out the MFA to be honest, but if it works for you, then should be fine. Thanks for the contribution!

2025-01-07 14:22 UTC, ehmsen commented
Thanks! No need to test MFA since if it does not work, then it is a garth problem :-)